### ISSUE TITLE
Index annotations and sdn6

### ISSUE THREAD

**Issue by shanon84** [michael-simons/neo4j-migrations#1191]
hey,
we have a catalog fulltext annotation to create a fulltext index now.
As I am looking more into sdn6 I cannot find any other index annotation (and I do not want to mix ogm, sdn6 and catalog),
Should we introduce two further annotations to: create a property index and to create a text index? To be able to generate all catalog based migrations based of the node classes? Or should it be a more genric aproach: @Index annotation with a type based of Index.Type enum?

**Comment by michael-simons** [comment]
Hm, I think you can just use the catalog indexes, can't you?

**Comment by shanon84** [comment]
you mean creating the index in xml directly? Sure, but I prefer to have everything inside the code/model itself. You cannot forget/overlook something so easyly.
Or do you mean something different?

**Comment by michael-simons** [comment]
Ok, got you. 

I wouldn't mind you rewriting the `@Fulltext` you introduced into an `@Index` so that

- it takes the analyzer into the options
- takes an enum value as type
- and is used to derive the the creation of the actual index objects as done in the processor

It's good that you brought this up, as the `@Fulltext` is not yet released and I would like to not deprecate it from the start.

**Comment by shanon84** [comment]
I have created a PR:
https://github.com/michael-simons/neo4j-migrations/pull/1192
I tried a more annotation based aproach for the options, but changed it back to this one.

**Comment by michael-simons** [comment]
Thanks a lot for your continued contribution. Merged as 8048557
