### ISSUE TITLE
Support for CALL subqueries in transactions

### ISSUE THREAD

**Issue by ctytgat** [michael-simons/neo4j-migrations#1537]
I need to run a large migration and want to use the CALL subqueries in transaction statement.

https://neo4j.com/docs/cypher-manual/5/subqueries/subqueries-in-transactions/

Putting this in a .cypher file generates an error 
`Caused by: org.neo4j.driver.exceptions.DatabaseException: A query with 'CALL { ... } IN TRANSACTIONS' can only be executed in an implicit transaction, but tried to execute in an explicit transaction.`

It looks like this is not supported?
Or how should we do this?

Using version 2.14 and neo4j 5.23

**Comment by michael-simons** [comment]
It should actually work https://github.com/michael-simons/neo4j-migrations/blob/7903f347ec3caf9860287d14e89a141d2adfbce8/neo4j-migrations-core/src/main/java/ac/simons/neo4j/migrations/core/DefaultCypherResource.java#L351-L353

Can you share you query?

**Comment by ctytgat** [comment]
This is what I tried:
`MATCH (type:AssetType) MATCH (a:Asset)-[:ASSET_TYPE]->(type)
CALL (a, type) {
CALL apoc.create.setLabels(a, [ type.name ] ) yield node
} IN 2 CONCURRENT TRANSACTIONS OF 1000 ROWS;`

**Comment by michael-simons** [comment]
@all-contributors please add @ctytgat for bug

**Comment by michael-simons** [comment]
@all-contributors please add @ctytgat for bug

**Comment by michael-simons** [comment]
Thanks for your input here.

As you might see in my comment on the commit, I am not the biggest fan of that control statement in a declarative query language, not in this context, not at all :), hence I just forgot about to check for this too, ever since our product is able to digest it.

I also needed to cater for the new importing syntax, which you also used (which is neat!).

This will be released soon.

Btw, since Neo4j 5.24 you can spare yourself APOC for setting dynamic labels, there's a new feature that does this in native Cypher

https://neo4j.com/docs/cypher-manual/current/clauses/set/#set-set-a-dynamic-label-on-a-node

**Comment by ctytgat** [comment]
Thanks for the fast response 🙂
