### ISSUE TITLE
Question: neo4j-migrations + SDN + Harness + Application Tests

### ISSUE THREAD

**Issue by mdelmoral** [michael-simons/neo4j-migrations#213]
Hi Michael,

I've been working with neo4j in Java environment for a few months now and I love the work you and your mates are doing. I already wrote some issues in the SDN project before and you (and your team) answer quickly.

I'm trying to add neo4j-migrations to my project to make changes automatically and don't forget them in the deployments 😅
The problem that I have is to integrate neo4j-migrations with the tests, both at the application and the service level.
I saw in this project that the tests are using TestContainers but I would like some similar with neo4j-harness.

The application.yml file has for the test profile:
```
spring.config.activate.on-profile: test
spring.neo4j.uri: bolt://localhost:6666
```

For the **service tests** I have the next configuration:
```
@DataNeo4jTest
@ActiveProfiles("test")
public class MyServiceTest {
    private final static String HOSTNAME = "localhost";

    private final static int PORT = 6666;

    protected static Neo4j embeddedDatabaseServer;

    protected static void initializeNeo4j() {
        initializeNeo4j(null);
    }

    protected static void initializeNeo4j(@Nullable String file) {
        try {
            var pluginDir = new File(ApocConfig.class.getProtectionDomain().getCodeSource().getLocation().toURI()).getParentFile().toPath();
            Neo4jBuilder neo4JBuilder = Neo4jBuilders
                    .newInProcessBuilder()
                    .withDisabledServer()
                    .withConfig(BoltConnector.listen_address, new SocketAddress(HOSTNAME, PORT))
                    .withConfig(GraphDatabaseSettings.plugin_dir, pluginDir)
                    .withConfig(GraphDatabaseSettings.procedure_unrestricted, List.of("apoc.*"));

            if (file != null) {
                var pathFixtureFile = Paths.get(AbstractNeo4jTestSupport.class.getClassLoader().getResource(file).getPath());
                neo4JBuilder.withFixture(pathFixtureFile);
            }

            embeddedDatabaseServer = neo4JBuilder.build();
        } catch (URISyntaxException e) {
            log.error("Error configuring Apoc Plugin", e);
        }
    }

    @BeforeAll
    public static void initDatabase() {
        initializeNeo4j();
    }

    @AfterAll
    static void closeNeo4j() {
        embeddedDatabaseServer.close();
    }
```
The tests work well but the migrations are never applied (there are no log traces).

For the **application tests** I have the next configuration:

```
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT, classes = Application.class)
public class MyControllerIT extends AbstractSpringContextAndNeo4jTestSupport {
```
`AbstractSpringContextAndNeo4jTestSupport` has the same previous configuration that the service tests but also _RestAssured_ is configured using the random port number and custom Jackson mappings injected in the application context load.
The tests are ok as well but I have the next errors in the log:
```
16949 --- [           main] a.s.n.m.s.b.a.MigrationsInitializer      : Cannot apply Neo4j migrations, driver instance cannot reach any database.

org.neo4j.driver.exceptions.ServiceUnavailableException: Unable to connect to localhost:6666, ensure the database is running and that there is a working network connection to it.
```
I think neo4j-migrations is trying to connect to the database before the instance is running.

If I change the annotations in `MyControllerIT` to  
```
@DataNeo4jTest
public class MyControllerIT extends AbstractSpringContextAndNeo4jTestSupport {
```
There are some necessary beans to configure RestAssured that are not injected (`@Autowired` doesn't work) and the tests crash.

Do you have some manual / tutorial where all of those pieces are combined? Thank you.

**Comment by michael-simons** [comment]
Hi Miquel.

`@DataNeo4jTest` does not know about this little project here, so it does not include it. Those test slices are meant to test only very specific parts of a Spring Boot application (in this case, Neo4j database connectivity related). 

Therefore, you need to import the auto configuration explicitly. 

This is done like this:

https://github.com/michael-simons/neo4j-migrations/blob/f3506bfc422a5bbcc15d5e1c15a7b874ba19f112/neo4j-migrations-examples/neo4j-migrations-examples-sb-testharness/src/test/java/org/neo4j/migrations/examples/sb/UsingDataNeo4jTest.java#L52

A dedicated test `application.yml` or properties combined with a profile works well for _static_ properties. Configuring dynamic properties - such as the port of a test container or embedded port, requires something different. It is a `@ DynamicPropertySource` (Spring Boot annotation) and it is used like this:

https://github.com/michael-simons/neo4j-migrations/blob/f3506bfc422a5bbcc15d5e1c15a7b874ba19f112/neo4j-migrations-examples/neo4j-migrations-examples-sb-testharness/src/test/java/org/neo4j/migrations/examples/sb/UsingDataNeo4jTest.java#L63-L68

In that example I use Harness 3.5 only because I wanted to stick to JDK8 for the main build, but that doesn't change the core concept.

In your test annotated with `@SpringBootTest` the migrations are applied (or at least, the context tries to apply them), because that test isn't only a slice, but the whole context, including all auto config that is found.

The thing fails because you don't configure an empty password which turns of authentication, which the harness doesn't provide out of the box.

The whole example is here: https://github.com/michael-simons/neo4j-migrations/tree/master/neo4j-migrations-examples/neo4j-migrations-examples-sb-testharness

Let me know if that helps. In general, I think at least the info about the slice plus migrations is worth mentioning in the readme.
