### ISSUE TITLE
Some openCypher based graphs do not support creating constraints with multi line transactions and throw errors when creating locks

### ISSUE THREAD

**Issue by karowan** [michael-simons/neo4j-migrations#256]
When creating the lock unique constraints, an error is thrown due to the constraints being created within a multi line transaction in some non-neo4j openCypher graph databases. The lines that would need to be changed are [these](https://github.com/michael-simons/neo4j-migrations/blob/master/neo4j-migrations-core/src/main/java/ac/simons/neo4j/migrations/core/MigrationsLock.java#L48-L54). Instead of running these within a single transaction, it requires them to be run individually.

**Comment by michael-simons** [comment]
Hmm?

**Comment by karowan** [comment]
I was contemplating on using this library for a non-neo4j openCypher based graph called memgraph but I realized that supporting those types of dbs are not necessarily within the scope of this project and so I retracted the issue. I apologize for the inconvenience.

**Comment by michael-simons** [comment]
No worries, all good.
I was unaware of Memgraph, seems to be a fork of Neo4j, at least it uses our Bolt protocol and appearantly is somewhat compatible with the driver.

The constraints are created inside one transaction for a reason: Either both or none at all.
I am doing this in a transactional function, so that the driver can retry if the thing fails due to cluster changes.

You are right, it is not necessary my goal to support other databases, however, I would have requested changes to the pr for the reason above.

What happens if you don't work on the session nor with a tx function but do a 

```java
Transaction tx = session.beginTransaction();
tx.run("CONSTRAINT1");
tx.run("CONSTRAINT2");
tx.commit();
```

would that work?

**Comment by karowan** [comment]
Unfortunately that does not work either. The queries to create the unique constraints must be a single line transaction and not be part of a group of queries. I do not think there would be a clean way to implement this transactionally that would conform to memgraph's restrictions so I feel as if it would be unfair to request for you to have those restrictions in mind whenever you add a new feature just for a relatively small offshoot of neo4j.
